"""
AFJEN statement corpus
CS4110 - Compiler Construction

The statements analysed by the project, grouped by the exam topics, each with a verified English and
French translation. Statements 1-15 were collected in Yaoundé; statements 16-30 are further typical
examples written for the project (source = "example") - replace them with statements your group heard
yourselves, or add your own in the app (they are stored in data/user_statements.json).
"""

from typing import Dict, List

TOPICS = [
    "Taxi & Commuting", "Poor Internet", "Electricity", "Market Bargaining", "Rainy Season", "Fuel Scarcity",
    "Roadside Business", "Bendskin", "Security Checkpoints", "ICT University", "Everyday Transactions",
]


def _s(n, topic, source, text, en, fr):
    return {"id": f"stmt_{n:03d}", "n": n, "topic": topic, "source": source, "text": text, "en": en, "fr": fr}


CORPUS: List[Dict[str, object]] = [
    _s(1, "Taxi & Commuting", "collected",
       "Brother, drop me na at Carrefour Yaoundé, the traffic done tire me small",
       "Brother, drop me off at Carrefour Yaoundé, the traffic has worn me out a bit.",
       "Frère, dépose-moi au carrefour de Yaoundé, les embouteillages m'ont un peu épuisé."),
    _s(2, "Taxi & Commuting", "collected",
       "Hala me small money, na five hundred francs remain for transport",
       "Give me a little money, I only have five hundred francs left for transport.",
       "Donne-moi un peu d'argent, il ne me reste que cinq cents francs pour le transport."),
    _s(3, "Taxi & Commuting", "collected",
       "Taxi! Yaoundé, Yaoundé! Fill am make we go, pas time dey waka!",
       "Taxi! Yaoundé, Yaoundé! Fill it up so we can go, time is running out!",
       "Taxi ! Yaoundé, Yaoundé ! Remplis-le pour qu'on puisse partir, le temps file !"),
    _s(4, "Poor Internet", "collected",
       "Eh mon Dieu, internet dey do again? I don try restart modem, garrr nothing!",
       "Oh my God, is the internet acting up again? I have tried restarting the modem, nothing, argh!",
       "Oh mon Dieu, Internet fait encore des siennes ? J'ai essayé de redémarrer le modem, rien, argh !"),
    _s(5, "Electricity", "collected",
       "The light done cut again, zéro-zéro, na generator we dey use since morning",
       "The power has gone out again, total blackout, we have been using a generator since morning.",
       "Le courant est encore coupé, coupure totale, on utilise un groupe électrogène depuis ce matin."),
    _s(6, "Poor Internet", "collected",
       "Je wanda why MTN network no fit work for this quarter, it's always down-down",
       "I wonder why the MTN network can't work in this neighbourhood, it's always down.",
       "Je me demande pourquoi le réseau MTN ne marche pas dans ce quartier, il est toujours en panne."),
    _s(7, "Market Bargaining", "collected",
       "Mama, make you reduce am na small, two thousand francs too much for tomatoes, ekiee",
       "Mama, please reduce it a little, two thousand francs is too much for tomatoes, oh dear!",
       "Maman, baisse un peu le prix, deux mille francs c'est trop pour des tomates, oh là là !"),
    _s(8, "Market Bargaining", "collected",
       "Chop na fresh, fresh! Come take am now, I give you good price, no wahala",
       "The food is fresh, really fresh! Come and take it now, I'll give you a good price, no trouble.",
       "C'est frais, tout frais ! Viens le prendre maintenant, je te fais un bon prix, pas de souci."),
    _s(9, "Bendskin", "collected",
       "Brother, the bendskin dey charge too much, five hundred for two kilometers, c'est cher ooo",
       "Brother, the bendskin is charging too much, five hundred for two kilometres, that's expensive!",
       "Frère, le bendskin fait payer trop cher, cinq cents pour deux kilomètres, c'est cher !"),
    _s(10, "Security Checkpoints", "collected",
       "They say checkpoint ahead, document dey for front, make we be careful pass",
       "They say there is a checkpoint ahead, the documents are at the front, let's be extra careful.",
       "On dit qu'il y a un contrôle devant, les papiers sont devant, soyons encore plus prudents."),
    _s(11, "Rainy Season", "collected",
       "Rain don fall so, the road done become mud, car stuck for quartier Mambanda",
       "It has rained so much, the road has turned to mud, a car is stuck in the Mambanda neighbourhood.",
       "Il a tellement plu, la route est devenue de la boue, une voiture est coincée au quartier Mambanda."),
    _s(12, "Fuel Scarcity", "collected",
       "Petrol dey scarce, pump don empty again, we go wait small before go fill tank",
       "Petrol is scarce, the pump has run empty again, we will wait a little before going to fill the tank.",
       "L'essence est rare, la pompe est encore vide, on va attendre un peu avant d'aller faire le plein."),
    _s(13, "Everyday Transactions", "collected",
       "How much for this phone airtime? OK, load me two thousand balance make I browse",
       "How much for this phone airtime? OK, load two thousand credit for me so I can browse.",
       "C'est combien ce crédit téléphonique ? OK, mets-moi deux mille de crédit pour que je puisse naviguer."),
    _s(14, "ICT University", "collected",
       "Lecture done start, prof say come sit down, but the class dey too crowded, hmmm",
       "The lecture has started, the professor said to come and sit down, but the class is too crowded, hmm.",
       "Le cours a commencé, le prof a dit de venir s'asseoir, mais la classe est trop pleine, hmm."),
    _s(15, "ICT University", "collected",
       "After exam finish, we go for beer na, relax small, this semester done tire me",
       "After the exam is over, we will go for a beer, relax a little, this semester has worn me out.",
       "Après l'examen, on ira prendre une bière, se détendre un peu, ce semestre m'a épuisé."),
    # ---- further examples ------------------------------------------------------------------------------
    _s(16, "Taxi & Commuting", "example",
       "Driver, stop for junction, I don reach",
       "Driver, stop at the junction, I have arrived.",
       "Chauffeur, arrêtez-vous au carrefour, je suis arrivé."),
    _s(17, "Taxi & Commuting", "example",
       "The taxi dey full, we go wait for another one",
       "The taxi is full, we will wait for another one.",
       "Le taxi est plein, on va en attendre un autre."),
    _s(18, "Bendskin", "example",
       "Bendskin man, wait here small, I go come now",
       "Bendskin driver, wait here a moment, I'll be right back.",
       "Conducteur de bendskin, attends ici un instant, je reviens tout de suite."),
    _s(19, "Poor Internet", "example",
       "Network dey bad again, I no fit send the message",
       "The network is bad again, I can't send the message.",
       "Le réseau est encore mauvais, je n'arrive pas à envoyer le message."),
    _s(20, "Electricity", "example",
       "Light don go since morning, we dey use candle",
       "The power has been out since morning, we are using a candle.",
       "Il n'y a plus de courant depuis ce matin, on s'éclaire avec une bougie."),
    _s(21, "Market Bargaining", "example",
       "Sister, how much for this fish? Abeg reduce am small",
       "Sister, how much for this fish? Please reduce it a little.",
       "Ma sœur, c'est combien ce poisson ? S'il te plaît, baisse un peu le prix."),
    _s(22, "Rainy Season", "example",
       "Rain dey fall plenty, my shoe don wet",
       "It is raining a lot, my shoes are wet.",
       "Il pleut beaucoup, mes chaussures sont mouillées."),
    _s(23, "Rainy Season", "example",
       "The gutter don block, water dey enter the shop",
       "The gutter is blocked, water is coming into the shop.",
       "Le caniveau est bouché, l'eau entre dans la boutique."),
    _s(24, "Fuel Scarcity", "example",
       "Fuel don finish for the station, we go queue tomorrow",
       "The fuel has run out at the station, we will queue tomorrow.",
       "Il n'y a plus de carburant à la station, on fera la queue demain."),
    _s(25, "Fuel Scarcity", "example",
       "Fuel don increase again, transport go cost more",
       "Fuel prices have gone up again, transport will cost more.",
       "Le carburant a encore augmenté, le transport va coûter plus cher."),
    _s(26, "Roadside Business", "example",
       "Madam, fry the fish well well, I dey wait",
       "Madam, fry the fish well, I am waiting.",
       "Madame, faites bien frire le poisson, j'attends."),
    _s(27, "Roadside Business", "example",
       "Brother, the suya dey sweet, give me one more",
       "Brother, the suya is delicious, give me one more.",
       "Frère, le suya est délicieux, donne-m'en un autre."),
    _s(28, "Security Checkpoints", "example",
       "Officer, my paper dey complete, abeg make I go",
       "Officer, my papers are complete, please let me go.",
       "Monsieur l'agent, mes papiers sont complets, laissez-moi passer, s'il vous plaît."),
    _s(29, "Security Checkpoints", "example",
       "Police dey for the roadblock, prepare your document",
       "The police are at the roadblock, get your documents ready.",
       "La police est au barrage, préparez vos papiers."),
    _s(30, "ICT University", "example",
       "Prof don come, make we enter the class quick quick",
       "The professor has arrived, let's get into class quickly.",
       "Le prof est arrivé, entrons vite en classe."),
]


def texts() -> List[str]:
    return [str(c["text"]) for c in CORPUS]
